apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: car-api-external-secret
  namespace: pycodebr
spec:
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: car-api-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: postgresql+psycopg://postgres:{{ .PASSWORD }}@pycodebr-rds.cxft3tnagyfp.us-east-1.rds.amazonaws.com:5432/postgres
        JWT_SECRET_KEY: "{{ .JWT_SECRET_KEY }}"
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: /pycodebr/car-api/rds/password
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /pycodebr/car-api/app/jwt_secret_key