---
apiVersion: v1
kind: Secret
metadata:
  name: car-api-secret
  namespace: pycodebr
stringData:
  DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/postgres
  JWT_SECRET_KEY: wTbYbLCrdJG1eE
