{{- if .Values.local.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: car-api-secret
  labels:
    {{- include "car-api.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: postgresql+psycopg://postgres:postgres@car-api-postgresql:5432/postgres
  JWT_SECRET_KEY: wTbYbLCrdJG1eE
{{- end }}
