{{- if not .Values.local.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "car-api.fullname" . }}-external-secret
  labels:
    {{- include "car-api.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: car-api-secret
    template:
      engineVersion: v2
      data:
        {{- range $es := .Values.externalSecrets }}
        {{ $last := splitList "/" $es | last | upper }}
        {{- if eq $last "PASSWORD" }}
        DATABASE_URL: postgresql+psycopg://postgres:{{ printf "{{ .%s }}" $last }}@db:5432/postgres
        {{- else }}
        {{ $last }}: "{{ printf "{{ .%s }}" $last }}"
        {{- end }}
        {{- end }}
  data:
    {{- range $es := .Values.externalSecrets }}
    - secretKey: {{ splitList "/" $es | last | upper }}
      remoteRef:
        key: {{ $es }}
    {{- end }}
{{- end }}
